# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcf0803b9927b949891200ee4c7623cfcbe8dc3ac1e57ac23d7662400a2b49e8f959f538d86fa24e442661cafacb7e852a6c1bb738a87a3483a46d63d4aadf74

test:
  secret_key_base: 7dc346a63d3dba70241c6d5bb84c368df7c80f92f6a663d71ca0155ea8238aa142ebeb63fd28fc16cfba82d07ad1b2871a683cbcf9541c2620c58a91c8dab4b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
